import { Link, NavLink, Outlet, useNavigate } from 'react-router-dom';
import { useAuth } from '../context/AuthContext';

const links = [{ label: 'Dashboard', to: '/admin', mark: '01' }, { label: 'Categories', to: '/admin/categories', mark: '02' }, { label: 'Products', to: '/admin/products', mark: '03' }, { label: 'Gallery', to: '/admin/gallery', mark: '04' }, { label: 'Inquiries', to: '/admin/inquiries', mark: '05' }, { label: 'Settings', to: '/admin/settings', mark: '06' }];

function AdminLayout() {
  const { user, logout } = useAuth();
  const navigate = useNavigate();
  const handleLogout = () => { logout(); navigate('/admin/login'); };
  return <div className="admin-shell min-h-screen bg-slate-100 lg:grid lg:grid-cols-[270px_1fr]"><aside className="border-b border-slate-800 bg-slate-950 p-4 text-slate-300 lg:sticky lg:top-0 lg:h-screen lg:border-b-0 lg:p-6"><div className="flex items-center justify-between lg:block"><Link to="/admin" className="flex items-center gap-3 text-white"><img src="/Logo.jpeg" alt="SAI TRADER Logo" className="h-10 w-auto object-contain" /><span className="text-lg font-extrabold leading-5">SAI TRADER<span className="mt-1 block text-[10px] font-bold tracking-[.18em] text-orange-400">ADMIN CONSOLE</span></span></Link><span className="rounded-md bg-white/10 px-2 py-1 text-[10px] font-bold text-slate-400 lg:hidden">MENU</span></div><nav className="mt-4 hidden gap-2 overflow-x-auto pb-1 lg:mt-10 lg:flex lg:flex-col lg:gap-2 lg:overflow-visible" aria-label="Admin navigation">{links.map((link) => <NavLink key={link.to} to={link.to} end={link.to === '/admin'} className={({ isActive }) => `flex shrink-0 items-center gap-3 rounded-xl px-3 py-2.5 text-sm font-bold transition lg:px-4 lg:py-3 ${isActive ? 'bg-blue-600 text-white shadow-lg shadow-blue-950/30' : 'bg-white/5 text-slate-300 hover:bg-slate-800 hover:text-white'}`}><span className={`text-[10px] ${link.to === '/admin' ? 'text-blue-100' : 'text-orange-400'}`}>{link.mark}</span>{link.label}</NavLink>)}</nav><div className="mt-8 hidden rounded-2xl border border-white/10 bg-white/5 p-4 lg:block"><p className="text-xs font-bold text-slate-500">Need to add website content?</p><Link to="/admin/products" className="mt-3 inline-block text-sm font-extrabold text-orange-400 hover:text-orange-300">Add a product →</Link></div></aside><div className="min-w-0"><header className="flex items-center justify-between border-b border-slate-200 bg-white px-4 py-4 sm:px-6 lg:px-8"><div><p className="text-sm font-extrabold text-slate-900">Welcome back, {user?.name || 'Admin'}</p><p className="mt-0.5 text-xs text-slate-500">SAI TRADER business management</p></div><button type="button" onClick={handleLogout} className="rounded-lg border border-slate-300 bg-white px-3 py-2 text-xs font-extrabold text-slate-700 transition hover:border-orange-500 hover:text-orange-600 sm:px-4 sm:text-sm">Logout</button></header><main className="p-4 sm:p-6 lg:p-8"><Outlet /></main></div></div>;
}

export default AdminLayout;
