services:
  - type: web
    name: plastic-business-management-api
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: COMPANY_EMAIL
        sync: false
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASS
        sync: false
      - key: API_URL
        value: https://plastic-business-management-api.onrender.com
      - key: NODE_ENV
        value: production
    healthCheckPath: /api/health
