import { useEffect, useState } from 'react';
import { createCategory, deleteCategory, getCategories, updateCategory } from '../../../services/categoryService';

const initialForm = { name: '', description: '', displayOrder: 0, isActive: true };

function Categories() {
  const [categories, setCategories] = useState([]);
  const [form, setForm] = useState(initialForm);
  const [editingId, setEditingId] = useState(null);
  const [message, setMessage] = useState('');
  const [isLoading, setIsLoading] = useState(true);

  const loadCategories = async () => { try { const response = await getCategories(); console.log('Categories response:', response); setCategories(response.data.data); } catch (error) { console.error('Error loading categories:', error); setMessage(error.response?.data?.message || 'Unable to load categories.'); } finally { setIsLoading(false); } };
  useEffect(() => { loadCategories(); }, []);
  const handleChange = (event) => { const { name, value, type, checked } = event.target; setForm((current) => ({ ...current, [name]: type === 'checkbox' ? checked : value })); };
  const resetForm = () => { setForm(initialForm); setEditingId(null); };
  const handleSubmit = async (event) => { event.preventDefault(); setMessage(''); try { const payload = { ...form, displayOrder: Number(form.displayOrder) }; const response = editingId ? await updateCategory(editingId, payload) : await createCategory(payload); setMessage(response.data.message); resetForm(); await loadCategories(); } catch (error) { setMessage(error.response?.data?.message || 'Unable to save category.'); } };
  const handleEdit = (category) => { setEditingId(category._id); setForm({ name: category.name, description: category.description || '', displayOrder: category.displayOrder, isActive: category.isActive }); window.scrollTo({ top: 0, behavior: 'smooth' }); };
  const handleDelete = async (id) => { if (!window.confirm('Delete this category?')) return; try { const response = await deleteCategory(id); setMessage(response.data.message); await loadCategories(); } catch (error) { setMessage(error.response?.data?.message || 'Unable to delete category.'); } };

  return <div className="max-w-6xl"><p className="text-sm font-extrabold uppercase tracking-[0.16em] text-orange-500">Content management</p><h1 className="mt-2 text-3xl font-extrabold text-slate-950">Categories</h1><p className="mt-2 text-slate-600">Create the application groups shown across the public website.</p><div className="mt-8 grid gap-6 lg:grid-cols-[0.9fr_1.1fr]"><section className="rounded-xl border border-slate-200 bg-white p-6 shadow-sm"><h2 className="text-xl font-extrabold text-slate-900">{editingId ? 'Edit category' : 'Add category'}</h2><form className="mt-6 space-y-4" onSubmit={handleSubmit}><Field label="Category name" name="name" value={form.name} onChange={handleChange} required /><Field label="Description" name="description" value={form.description} onChange={handleChange} /><Field label="Display order" name="displayOrder" type="number" value={form.displayOrder} onChange={handleChange} /><label className="flex items-center gap-3 text-sm font-bold text-slate-700"><input name="isActive" type="checkbox" checked={form.isActive} onChange={handleChange} className="h-4 w-4 accent-blue-700" />Active on website</label>{message && <p className="rounded-lg bg-blue-50 px-3 py-2 text-sm font-semibold text-blue-800">{message}</p>}<div className="flex gap-3"><button className="rounded-lg bg-blue-700 px-4 py-3 text-sm font-extrabold text-white hover:bg-blue-800">{editingId ? 'Update Category' : 'Add Category'}</button>{editingId && <button type="button" onClick={resetForm} className="rounded-lg border border-slate-300 px-4 py-3 text-sm font-extrabold text-slate-700">Cancel</button>}</div></form></section><section className="overflow-hidden rounded-xl border border-slate-200 bg-white shadow-sm"><div className="border-b border-slate-200 px-6 py-5"><h2 className="font-extrabold text-slate-900">Saved categories</h2></div>{isLoading ? <p className="p-6 text-slate-500">Loading categories...</p> : categories.length === 0 ? <p className="p-6 text-slate-500">No categories yet. Add your first category from the form.</p> : <div className="divide-y divide-slate-100">{categories.map((category) => <article key={category._id} className="flex items-start justify-between gap-4 p-5"><div><h3 className="font-extrabold text-slate-900">{category.name}</h3><p className="mt-1 text-sm leading-6 text-slate-600">{category.description || 'No description added.'}</p><p className="mt-2 text-xs font-bold text-slate-400">Order: {category.displayOrder} · {category.isActive ? 'Active' : 'Hidden'}</p></div><div className="flex gap-2"><button onClick={() => handleEdit(category)} className="rounded-lg border border-blue-200 px-3 py-2 text-xs font-extrabold text-blue-700">Edit</button><button onClick={() => handleDelete(category._id)} className="rounded-lg border border-red-200 px-3 py-2 text-xs font-extrabold text-red-600">Delete</button></div></article>)}</div>}</section></div></div>;
}

function Field({ label, name, value, onChange, type = 'text', required = false }) { return <label className="block text-sm font-bold text-slate-700">{label}<input required={required} name={name} type={type} value={value} onChange={onChange} className="mt-2 w-full rounded-lg border border-slate-300 px-3 py-2.5 font-normal outline-none focus:border-blue-600 focus:ring-2 focus:ring-blue-100" /></label>; }

export default Categories;
